name : mysecondworkflow
on:
  push:
    branches:
      - main

jobs:
         my-first-jobs:
            runs-on : ubuntu-latest
            steps:
                 - name : show trigger
                   run:  echo "have been triggered by ${{ github.event_name }} event"
   
